# Generated by Django 4.2.3 on 2023-08-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='not avaiable', max_length=100),
        ),
    ]
