# Generated by Django 4.2.3 on 2023-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_filled',
            field=models.BooleanField(default=False),
        ),
    ]
